volumes:
  app_local_postgres_data: {}
  app_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: app_local_django
    container_name: app_local_django
    depends_on:
      - postgres
      - redis
      - mailhog
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    image: app_production_postgres
    container_name: app_local_postgres
    volumes:
      - app_local_postgres_data:/var/lib/postgresql/data
      - app_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: app_local_mailhog
    ports:
      - "8025:8025"

  redis:
    image: redis:6
    container_name: app_local_redis
